name: CI

on: [push, pull_request]

jobs:
  bigsur:
    name: arm64-candi test
    runs-on: [self-hosted]

    steps:
    - uses: actions/checkout@v2
    - name: setup
      run: |
        #
        #brew install wget gnuplot cmake openmpi modules vim trash gcc@9

        export OMPI_CXX=g++-9
        export OMPI_CC=gcc-9
        export OMPI_FC=gfortran
        echo 'DEAL_II_CONFOPTS="-D CMAKE_BUILD_TYPE=Debug"' >> candi.cfg
        git clone  https://github.com/dealii/candi.git
        cd candi
        ./candi.sh  -j 6 --packages="dealii" --platform=deal.II-toolchain/platforms/supported/catalina.platform



